export interface KnowledgeSketch {
  slug: string;
  title: string;
  question: string;
  thesis: string;
  nodes: string[];
  flow: string[];
  note: string;
  accent: string;
}

export interface SketchModule {
  moduleDir: string;
  moduleId: string;
  moduleName: string;
  icon: string;
  aiLens: string;
  sketches: KnowledgeSketch[];
}

export interface SketchTrack {
  id: string;
  name: string;
  icon: string;
  lens: string;
  sketches: KnowledgeSketch[];
}

export const AI_SUPPLEMENT_POINTS = [
  {
    title: '表示与压缩',
    desc: '从 token、embedding、latent space 到量化，理解模型如何把世界压进向量空间。',
  },
  {
    title: '上下文与记忆',
    desc: '区分上下文窗口、KV Cache、外部记忆、长期偏好与可追溯知识库。',
  },
  {
    title: '评测与校准',
    desc: '把离线 benchmark、在线反馈、幻觉检测、置信度与业务指标连起来。',
  },
  {
    title: '系统边界',
    desc: '看清模型、工具、权限、数据、调度、成本之间的边界和失败模式。',
  },
  {
    title: '交互协议',
    desc: 'Prompt、tool schema、MCP、事件流与状态机决定 AI 能否稳定参与工作流。',
  },
  {
    title: '经济学视角',
    desc: '训练成本、推理成本、延迟、吞吐、缓存命中率和用户体验是同一个系统问题。',
  },
];

export const IAAS_TRANSITION_TRACKS: SketchTrack[] = [
  {
    id: 'iaas-ai-mental-model',
    name: '从 IaaS 到 AI 架构心智',
    icon: '🧭',
    lens: 'IaaS 架构师的优势是资源、网络、稳定性和成本；转 AI 架构要把这些能力映射到 token、模型、数据和 GPU 集群。',
    sketches: [
      {
        slug: 'vm-to-token',
        title: '从 VM 资源到 Token 工厂',
        question: 'AI 系统到底在生产什么？',
        thesis: '传统 IaaS 交付 vCPU、内存、磁盘和网络，AI 架构最终交付稳定、低成本、可追溯的 token。',
        nodes: ['IaaS 资源池', '模型运行时', 'Token 产出'],
        flow: ['VM/容器', 'GPU Pod', '推理服务', 'Token'],
        note: '先把“算力交付”改成“智能吞吐交付”。',
        accent: '#f59e0b',
      },
      {
        slug: 'control-plane-shift',
        title: '控制面从机器转向任务',
        question: '为什么 AI 平台不能只管机器？',
        thesis: 'AI 控制面要理解训练任务、推理副本、模型版本、数据集、评测和配额。',
        nodes: ['资源控制面', '任务控制面', '模型控制面'],
        flow: ['申请', '编排', '观测', '回收'],
        note: 'AI 平台控制面必须认识“模型生命周期”。',
        accent: '#38bdf8',
      },
      {
        slug: 'ops-to-product-contract',
        title: '运维能力要产品化',
        question: '转型的第一道坎是什么？',
        thesis: '把装机、扩容、巡检、排障和成本分析沉淀成平台能力，而不是靠个人经验救火。',
        nodes: ['SOP', 'API', '自助门户'],
        flow: ['经验', '标准', '自动化', '产品'],
        note: 'AI 架构师要把运维经验变成可调用能力。',
        accent: '#fb7185',
      },
    ],
  },
  {
    id: 'iaas-ai-capacity',
    name: '容量规划与算力画像',
    icon: '📐',
    lens: 'AI 容量规划不只看 CPU/内存利用率，而要同时看 GPU 显存、HBM 带宽、网络通信、KV Cache 和 token 曲线。',
    sketches: [
      {
        slug: 'gpu-sizing-triangle',
        title: 'GPU 选型三角',
        question: '买什么卡才算合适？',
        thesis: '训练看显存与互联，推理看显存、带宽和并发，研发看可用性与生态。',
        nodes: ['显存容量', '互联带宽', '软件生态'],
        flow: ['场景', '模型', '并发', '卡型'],
        note: '不要用单一 TFLOPS 决定 AI 基础设施。',
        accent: '#22c55e',
      },
      {
        slug: 'training-capacity-map',
        title: '训练容量按阶段拆',
        question: '训练集群容量怎么估？',
        thesis: '预训练、SFT、RLHF、评测和数据处理对 GPU、存储、网络的压力完全不同。',
        nodes: ['训练阶段', '并行策略', '检查点'],
        flow: ['数据', '训练', '评测', '发布'],
        note: '容量表要按作业类型建，而不是按部门拍。',
        accent: '#60a5fa',
      },
      {
        slug: 'inference-capacity-map',
        title: '推理容量看 Token 曲线',
        question: '推理容量为什么难估？',
        thesis: '输入长度、输出长度、并发、缓存命中和 SLO 会共同改变 GPU 容量需求。',
        nodes: ['TTFT', 'TPOT', 'KV Cache'],
        flow: ['请求分布', '服务参数', '压测', '容量池'],
        note: 'QPS 不够，要看每秒 token 和尾延迟。',
        accent: '#e24a3b',
      },
    ],
  },
  {
    id: 'iaas-ai-network-storage',
    name: '网络与存储重构',
    icon: '🕸️',
    lens: 'AI 的慢常常不在模型，而在数据和通信路径；IaaS 网络/存储经验要升级成面向训练和推理的数据平面设计。',
    sketches: [
      {
        slug: 'east-west-ai-traffic',
        title: '东西向流量变成主角',
        question: 'AI 集群网络哪里不同？',
        thesis: '梯度同步、参数加载、KV Cache 迁移和数据分发让东西向流量成为关键路径。',
        nodes: ['AllReduce', '数据加载', 'Cache 迁移'],
        flow: ['GPU', '交换机', 'GPU', '作业'],
        note: 'AI 网络先看拓扑和拥塞，再看出口带宽。',
        accent: '#38bdf8',
      },
      {
        slug: 'dataset-checkpoint-storage',
        title: '存储要服务数据生命周期',
        question: '为什么普通共享盘不够？',
        thesis: '数据集、特征、检查点、模型权重和日志需要不同吞吐、延迟、冷热分层策略。',
        nodes: ['数据集', 'Checkpoint', '模型仓库'],
        flow: ['采集', '清洗', '训练', '归档'],
        note: '训练存储要按生命周期设计，不是只堆容量。',
        accent: '#f59e0b',
      },
      {
        slug: 'data-gravity',
        title: '数据重力决定架构位置',
        question: '训练和推理应该放哪里？',
        thesis: '数据所在位置、合规边界、网络成本和延迟决定 AI 工作负载的部署形态。',
        nodes: ['数据位置', '合规边界', '延迟成本'],
        flow: ['数据源', '计算池', '模型服务', '用户'],
        note: 'AI 架构不是“哪里有卡放哪里”。',
        accent: '#14b8a6',
      },
    ],
  },
  {
    id: 'iaas-ai-platform-sre',
    name: 'AI 平台 SRE',
    icon: '📟',
    lens: 'AI SRE 要把传统基础设施指标、模型行为指标和业务体验指标串成一条因果链。',
    sketches: [
      {
        slug: 'ai-slo-stack',
        title: 'AI SLO 分三层',
        question: 'AI 服务怎么定 SLO？',
        thesis: '基础设施可用性、模型服务延迟、回答质量和业务成功率要分层定义。',
        nodes: ['Infra SLO', 'Serving SLO', 'Quality SLO'],
        flow: ['GPU 健康', 'Token 延迟', '答案质量', '业务结果'],
        note: '只看 99.9% 可用，解释不了 AI 好不好用。',
        accent: '#60a5fa',
      },
      {
        slug: 'gpu-incident-playbook',
        title: 'GPU 故障要有剧本',
        question: 'GPU 出问题怎么不靠猜？',
        thesis: 'ECC、Xid、温度、链路、驱动、NCCL 和作业日志要进入统一排障剧本。',
        nodes: ['硬件事件', '链路状态', '作业影响'],
        flow: ['告警', '定位', '隔离', '恢复'],
        note: 'AI 故障排查要能从作业追到硬件。',
        accent: '#fb7185',
      },
      {
        slug: 'quality-observability',
        title: '质量观测不能缺席',
        question: '服务正常但回答差怎么办？',
        thesis: '召回命中、上下文长度、拒答率、幻觉率和用户反馈是 AI 服务的业务健康指标。',
        nodes: ['召回命中', '幻觉检测', '用户反馈'],
        flow: ['请求', '检索', '生成', '评分'],
        note: 'AI 平台观测要跨过基础设施边界。',
        accent: '#a78bfa',
      },
    ],
  },
  {
    id: 'iaas-ai-security',
    name: '安全、隔离与治理',
    icon: '🛡️',
    lens: 'AI 安全不是只加网关；它覆盖数据、模型、提示词、工具权限、租户隔离和输出治理。',
    sketches: [
      {
        slug: 'tenant-isolation-ai',
        title: '租户隔离延伸到模型',
        question: '多租户 AI 平台隔离什么？',
        thesis: '除了网络和磁盘，还要隔离数据集、模型权重、向量索引、工具凭证和推理上下文。',
        nodes: ['数据隔离', '模型隔离', '工具隔离'],
        flow: ['租户', '权限', '运行时', '审计'],
        note: 'AI 多租户的边界比 IaaS 更长。',
        accent: '#22c55e',
      },
      {
        slug: 'prompt-tool-risk',
        title: '提示词会触发权限风险',
        question: '为什么 Agent 更难管？',
        thesis: 'Prompt Injection 可能诱导模型调用工具、泄漏上下文或绕过业务流程。',
        nodes: ['Prompt', 'Tool', 'Policy'],
        flow: ['输入', '意图识别', '权限校验', '执行'],
        note: '工具调用前要有策略层，不要只信模型判断。',
        accent: '#e24a3b',
      },
      {
        slug: 'model-supply-chain',
        title: '模型也有供应链',
        question: '开源模型怎么治理？',
        thesis: '模型来源、许可证、权重校验、依赖镜像、评测记录和发布审批都要可追踪。',
        nodes: ['来源校验', '安全评测', '发布审批'],
        flow: ['下载', '扫描', '评测', '上线'],
        note: '模型仓库要像镜像仓库一样治理。',
        accent: '#38bdf8',
      },
    ],
  },
  {
    id: 'iaas-ai-cost-finops',
    name: '成本与 FinOps',
    icon: '💳',
    lens: 'AI 成本的单位从 VM 小时变成 GPU 小时、每千 token、每次训练和每次高质量回答。',
    sketches: [
      {
        slug: 'gpu-hour-to-token-cost',
        title: '从 GPU 小时算到 Token 成本',
        question: 'AI 成本怎么讲给业务听？',
        thesis: 'GPU 成本要折算到训练任务、推理 token、缓存命中和业务调用。',
        nodes: ['GPU 小时', 'Token 单价', '业务调用'],
        flow: ['资源账单', '作业标签', '服务指标', '成本归因'],
        note: 'AI FinOps 要让业务看懂每次智能的价格。',
        accent: '#f59e0b',
      },
      {
        slug: 'idle-gpu-waste',
        title: '闲置 GPU 是最大浪费',
        question: '为什么 AI 集群成本这么敏感？',
        thesis: '训练排队、低利用推理、碎片显存和错误配额都会让昂贵 GPU 空转。',
        nodes: ['排队浪费', '低利用率', '资源碎片'],
        flow: ['监控', '归因', '调度', '回收'],
        note: 'GPU 利用率要和有效 token/step 一起看。',
        accent: '#fb7185',
      },
      {
        slug: 'cost-quality-tradeoff',
        title: '成本和质量要一起调',
        question: '降本会不会伤效果？',
        thesis: '量化、缓存、小模型路由、RAG 和批处理都要在质量门槛下优化。',
        nodes: ['质量底线', '模型路由', '缓存策略'],
        flow: ['评测', '降本', '灰度', '复盘'],
        note: 'AI 降本不是砍资源，是做策略组合。',
        accent: '#84cc16',
      },
    ],
  },
  {
    id: 'iaas-ai-delivery',
    name: '交付路径与组织协作',
    icon: '🧩',
    lens: 'AI 架构交付不是“平台上线”就结束，而是让算法、平台、运维、安全、业务围绕模型生命周期协作。',
    sketches: [
      {
        slug: 'model-lifecycle-map',
        title: '模型生命周期要端到端',
        question: 'AI 平台交付边界在哪？',
        thesis: '数据准备、训练、评测、注册、部署、观测、回滚组成完整模型生命周期。',
        nodes: ['数据', '模型', '服务'],
        flow: ['准备', '训练', '评测', '上线'],
        note: 'AI 架构师要画生命周期，不只画部署图。',
        accent: '#2dd4bf',
      },
      {
        slug: 'cross-team-contract',
        title: '跨团队靠契约协作',
        question: '为什么 AI 项目容易卡？',
        thesis: '数据口径、模型接口、SLO、权限、评测标准和上线流程需要提前契约化。',
        nodes: ['数据契约', '服务契约', '评测契约'],
        flow: ['约定', '实现', '验证', '运营'],
        note: '没有契约，AI 平台会变成工单平台。',
        accent: '#60a5fa',
      },
      {
        slug: 'reference-architecture',
        title: '参考架构要可落地',
        question: 'AI 架构图应该画什么？',
        thesis: '一张好图要同时表达控制面、数据面、模型面、观测面、安全面和成本面。',
        nodes: ['控制面', '数据面', '治理面'],
        flow: ['用户', '平台', '模型', '反馈'],
        note: '架构图不是装饰，是协作接口。',
        accent: '#a78bfa',
      },
    ],
  },
  {
    id: 'iaas-ai-roadmap',
    name: '转型路线图',
    icon: '🗺️',
    lens: '转型 AI 架构不需要一次跨到算法专家，而是沿着“资源池化、平台化、模型服务化、智能应用化”逐步上台阶。',
    sketches: [
      {
        slug: 'first-30-days',
        title: '前 30 天补语言',
        question: '第一阶段学什么？',
        thesis: '建立 GPU、训练、推理、RAG、Agent、评测和成本的共同词汇表。',
        nodes: ['GPU 基础', 'LLM 推理', 'RAG/Agent'],
        flow: ['读图', '跑通', '记录', '复述'],
        note: '先能和算法、平台、业务说同一种话。',
        accent: '#38bdf8',
      },
      {
        slug: 'first-90-days',
        title: '90 天做一条链路',
        question: '怎么从知道变成会做？',
        thesis: '交付一个小型端到端链路：数据入库、模型服务、RAG、观测、成本看板。',
        nodes: ['端到端 Demo', '观测面板', '成本账本'],
        flow: ['需求', '搭建', '压测', '复盘'],
        note: '转型靠闭环项目，不靠概念堆叠。',
        accent: '#f59e0b',
      },
      {
        slug: 'first-180-days',
        title: '180 天形成平台能力',
        question: '怎么成为 AI 架构师？',
        thesis: '把 Demo 升级为可复用能力：模型网关、评测流水线、GPU 调度、知识库和 SRE 剧本。',
        nodes: ['模型网关', '评测流水线', 'SRE 剧本'],
        flow: ['标准化', '自动化', '治理', '规模化'],
        note: 'AI 架构师的标志是能让别人稳定交付 AI。',
        accent: '#fb7185',
      },
    ],
  },
];

export const SKETCH_MODULES: SketchModule[] = [
  {
    moduleDir: '01_hardware_architecture',
    moduleId: '01',
    moduleName: '硬件架构',
    icon: '⚡',
    aiLens: 'AI 眼里的硬件不是零件清单，而是矩阵乘法、显存带宽和跨卡通信的物理约束。',
    sketches: [
      {
        slug: 'gpu-as-matmul-engine',
        title: 'GPU 是矩阵乘法工厂',
        question: '为什么 AI 需要 GPU？',
        thesis: '大量相同形状的乘加运算，被 SM、Tensor Core 和 HBM 组织成流水线。',
        nodes: ['SM 调度线程块', 'Tensor Core 做乘加', 'HBM 喂数据'],
        flow: ['算子图', 'Kernel', 'Warp', '吞吐'],
        note: '先抓住计算密度，再看架构细节。',
        accent: '#f59e0b',
      },
      {
        slug: 'memory-wall',
        title: '显存墙决定速度上限',
        question: '算力很高，为什么还会慢？',
        thesis: '真正的瓶颈常常是数据移动：HBM、Cache、PCIe 和 CPU 内存之间的距离。',
        nodes: ['HBM 带宽', 'Cache 复用', 'PCIe 往返'],
        flow: ['数据布局', '访存模式', '复用率', '瓶颈'],
        note: 'AI 系统优化先问：数据在哪里？要搬几次？',
        accent: '#38bdf8',
      },
      {
        slug: 'multi-gpu-fabric',
        title: '多卡互联是第二块芯片',
        question: '一张卡不够时发生什么？',
        thesis: 'NVLink、NVSwitch、PCIe 和 RDMA 把多张 GPU 拼成一个不完美的大机器。',
        nodes: ['NVLink 低延迟', 'NVSwitch 扩展', 'RDMA 跨节点'],
        flow: ['单卡', '节点内', '跨节点', '集群'],
        note: '训练大模型时，通信拓扑就是模型的一部分。',
        accent: '#fb7185',
      },
    ],
  },
  {
    moduleDir: '02_gpu_programming',
    moduleId: '02',
    moduleName: 'GPU编程',
    icon: '🔧',
    aiLens: 'AI 眼里的 GPU 编程是把一个数学表达式翻译成可并行、少搬运、能排满硬件的执行计划。',
    sketches: [
      {
        slug: 'thread-hierarchy',
        title: '线程层级像排班表',
        question: 'CUDA 线程为什么分这么多层？',
        thesis: 'Grid、Block、Warp、Thread 是把大任务切成硬件可调度单位的语言。',
        nodes: ['Grid 管全局', 'Block 共享资源', 'Warp 同步执行'],
        flow: ['问题规模', '切块', '排班', '并行'],
        note: '写 Kernel 先设计任务切分。',
        accent: '#14b8a6',
      },
      {
        slug: 'memory-coalescing',
        title: '访存合并胜过蛮力',
        question: '为什么相同计算量速度差很多？',
        thesis: '连续访问、共享内存复用和减少分支发散，能让同样的算力更有效。',
        nodes: ['连续读取', '共享内存', '少分支'],
        flow: ['全局内存', 'Tile', '寄存器', '结果'],
        note: 'GPU 优化经常是“少等数据”。',
        accent: '#22c55e',
      },
      {
        slug: 'profiling-loop',
        title: 'Profiling 是编程闭环',
        question: '怎么知道 Kernel 卡在哪里？',
        thesis: '用 roofline、occupancy、memory throughput 和 timeline 找到下一步改哪里。',
        nodes: ['测量', '定位瓶颈', '改写 Kernel'],
        flow: ['Nsight', '指标', '假设', '验证'],
        note: '不要凭感觉优化，先看计数器。',
        accent: '#a78bfa',
      },
    ],
  },
  {
    moduleDir: '03_ai_cluster_operations',
    moduleId: '03',
    moduleName: 'AI集群运维',
    icon: '🖧',
    aiLens: 'AI 眼里的集群是一台会部分失灵的超级计算机，网络、调度和可观测性决定它能不能持续产出 token。',
    sketches: [
      {
        slug: 'cluster-as-computer',
        title: '集群是一台大计算机',
        question: '为什么单机经验不够用？',
        thesis: 'GPU 节点、交换网络、共享存储和调度系统共同组成训练机器。',
        nodes: ['GPU 节点', '高速网络', '共享存储'],
        flow: ['任务', '资源', '通信', '产出'],
        note: '运维的目标是让整机稳定而不是单点漂亮。',
        accent: '#38bdf8',
      },
      {
        slug: 'network-first',
        title: '网络是训练的血管',
        question: '为什么 NCCL 和 IB 这么重要？',
        thesis: 'AllReduce、参数同步和数据加载都会把网络抖动放大成训练抖动。',
        nodes: ['InfiniBand/RoCE', 'NCCL Ring/Tree', '拓扑感知'],
        flow: ['梯度', '聚合', '同步', '下一步'],
        note: '网络故障常表现为“模型训练变慢”。',
        accent: '#60a5fa',
      },
      {
        slug: 'ops-feedback-loop',
        title: '可观测性是免疫系统',
        question: '怎么提前发现集群要坏？',
        thesis: '指标、日志、拓扑、作业状态和告警要能串回同一个事件。',
        nodes: ['GPU 健康', '链路质量', '作业画像'],
        flow: ['采集', '关联', '告警', '修复'],
        note: 'AI 集群运维是数据产品，不只是脚本集合。',
        accent: '#f97316',
      },
    ],
  },
  {
    moduleDir: '04_cloud_native_ai_platform',
    moduleId: '04',
    moduleName: '云原生AI平台',
    icon: '☁️',
    aiLens: 'AI 眼里的平台是把不稳定的硬件能力包装成可申请、可隔离、可回收的产品接口。',
    sketches: [
      {
        slug: 'gpu-scheduling',
        title: 'GPU 调度是一场配座',
        question: 'K8s 为什么要懂 GPU？',
        thesis: '训练、推理、批任务和交互服务需要不同的卡型、拓扑和优先级。',
        nodes: ['资源声明', '拓扑约束', '队列优先级'],
        flow: ['Pod', '调度器', '节点', 'GPU'],
        note: '调度不是塞满，而是让任务拿到正确资源。',
        accent: '#a78bfa',
      },
      {
        slug: 'isolation-sharing',
        title: '共享与隔离要同时成立',
        question: '一张 GPU 能不能多人用？',
        thesis: 'MIG、时间片、显存限制和权限边界决定平台的安全与利用率。',
        nodes: ['MIG', 'vGPU', 'Quota'],
        flow: ['租户', '切分', '隔离', '审计'],
        note: '共享 GPU 的难点是性能、隔离和体验的三角平衡。',
        accent: '#84cc16',
      },
      {
        slug: 'platform-contract',
        title: '平台要提供稳定契约',
        question: 'AI 平台真正交付什么？',
        thesis: '镜像、数据、模型、密钥、日志、弹性和成本，要被封装成可复用工作流。',
        nodes: ['运行环境', '数据通道', '成本边界'],
        flow: ['开发', '训练', '部署', '回收'],
        note: '云原生 AI 的核心是把复杂性藏在契约后面。',
        accent: '#2dd4bf',
      },
    ],
  },
  {
    moduleDir: '05_model_training_and_fine_tuning',
    moduleId: '05',
    moduleName: '模型训练与微调',
    icon: '🎯',
    aiLens: 'AI 眼里的训练是把数据分布、目标函数和算力预算压成一组可泛化的参数。',
    sketches: [
      {
        slug: 'training-loop',
        title: '训练循环塑造模型',
        question: '模型怎么从数据里学会模式？',
        thesis: '样本经过前向、损失、反向传播和优化器，逐步改变参数。',
        nodes: ['数据批次', 'Loss 信号', '参数更新'],
        flow: ['Forward', 'Loss', 'Backward', 'Step'],
        note: '所有训练框架都绕不开这个核心循环。',
        accent: '#fb7185',
      },
      {
        slug: 'peft-lora',
        title: 'LoRA 是旁路改造',
        question: '为什么微调不一定要动全量参数？',
        thesis: '冻结主干权重，只训练低秩适配器，降低显存、成本和灾难性遗忘风险。',
        nodes: ['冻结主干', '低秩矩阵', '任务适配'],
        flow: ['基座模型', 'Adapter', '合并/挂载', '推理'],
        note: 'PEFT 的本质是用小改动改变行为。',
        accent: '#f59e0b',
      },
      {
        slug: 'parallelism-stack',
        title: '并行策略拆开巨模型',
        question: '模型大到放不下一张卡怎么办？',
        thesis: '数据并行、张量并行、流水线并行和 ZeRO 分别切不同维度。',
        nodes: ['数据并行', '张量并行', '流水线并行'],
        flow: ['参数', '激活', '梯度', '通信'],
        note: '并行不是越多越好，要看通信代价。',
        accent: '#60a5fa',
      },
    ],
  },
  {
    moduleDir: '06_llm_theory_and_foundation',
    moduleId: '06',
    moduleName: 'LLM理论与基础',
    icon: '🧠',
    aiLens: 'AI 眼里的理论不是公式收藏，而是解释 token 如何变成可预测、可控制、可评估的行为。',
    sketches: [
      {
        slug: 'token-attention',
        title: 'Token 通过注意力对话',
        question: 'Transformer 为什么强？',
        thesis: '每个 token 用 Q/K/V 询问上下文，层层组合出更高阶的表示。',
        nodes: ['Token', 'Q/K/V', '上下文表示'],
        flow: ['嵌入', '注意力', 'MLP', '输出'],
        note: '注意力解决的是“该看谁”。',
        accent: '#22c55e',
      },
      {
        slug: 'moe-routing',
        title: 'MoE 把能力分给专家',
        question: '稀疏模型为什么省算力？',
        thesis: '路由器只激活少数专家，让参数规模变大但每次计算保持可控。',
        nodes: ['Router', 'Experts', 'Top-k 激活'],
        flow: ['Token', '路由', '专家', '合并'],
        note: 'MoE 的关键风险是负载均衡和专家塌缩。',
        accent: '#e879f9',
      },
      {
        slug: 'evaluation-calibration',
        title: '评测要对齐真实行为',
        question: '分数高就一定好用吗？',
        thesis: '能力、可靠性、安全性、成本和场景约束必须一起评估。',
        nodes: ['离线题集', '在线反馈', '校准策略'],
        flow: ['样本', '指标', '误差分析', '改进'],
        note: '从 AI 本身看，评测就是外部世界给的学习信号。',
        accent: '#38bdf8',
      },
    ],
  },
  {
    moduleDir: '07_rag_and_tools',
    moduleId: '07',
    moduleName: 'RAG与工具',
    icon: '🔍',
    aiLens: 'AI 眼里的 RAG 是把私有知识、实时信息和可验证来源接到模型上下文里。',
    sketches: [
      {
        slug: 'rag-loop',
        title: 'RAG 是检索-生成闭环',
        question: '为什么不把知识都塞进模型？',
        thesis: '把问题转成检索意图，取回证据，再让模型带引用回答。',
        nodes: ['Query 改写', '召回排序', '证据生成'],
        flow: ['问题', '检索', '上下文', '回答'],
        note: 'RAG 的核心不是向量库，而是证据链。',
        accent: '#14b8a6',
      },
      {
        slug: 'chunking-index',
        title: '分块决定记忆颗粒度',
        question: '为什么同一个库效果差很多？',
        thesis: '文档解析、chunk 粒度、metadata 和 embedding 模型决定召回质量。',
        nodes: ['解析结构', 'Chunk 策略', 'Metadata'],
        flow: ['文档', '分块', '向量', '索引'],
        note: '垃圾分块会把好模型变成差系统。',
        accent: '#facc15',
      },
      {
        slug: 'graph-tool-rag',
        title: '图谱让检索有关系感',
        question: '什么时候需要 GraphRAG？',
        thesis: '实体、关系、路径和社区摘要能补上普通向量检索的结构盲区。',
        nodes: ['实体抽取', '关系边', '路径推理'],
        flow: ['文本', '图谱', '子图', '答案'],
        note: '图谱适合“关系比段落更重要”的问题。',
        accent: '#60a5fa',
      },
    ],
  },
  {
    moduleDir: '08_agentic_system',
    moduleId: '08',
    moduleName: '智能体系统',
    icon: '🤖',
    aiLens: 'AI 眼里的 Agent 是带目标、工具、记忆和反馈的运行时，而不只是一次聊天。',
    sketches: [
      {
        slug: 'plan-act-observe',
        title: 'Agent 循环像小型操作系统',
        question: 'Agent 和普通调用差在哪？',
        thesis: '规划、行动、观察和修正构成持续推进任务的控制回路。',
        nodes: ['Plan', 'Act', 'Observe'],
        flow: ['目标', '计划', '工具', '反馈'],
        note: '循环质量比单次 prompt 更重要。',
        accent: '#2dd4bf',
      },
      {
        slug: 'tool-contracts',
        title: '工具调用靠契约稳定',
        question: '为什么工具多了反而容易乱？',
        thesis: 'Schema、权限、错误语义、幂等性和审计决定工具能否被可靠组合。',
        nodes: ['Tool Schema', '权限边界', '错误恢复'],
        flow: ['意图', '参数', '调用', '结果'],
        note: 'MCP 的价值是把工具世界协议化。',
        accent: '#a78bfa',
      },
      {
        slug: 'agent-memory',
        title: '记忆分层决定连续性',
        question: 'Agent 如何不忘事？',
        thesis: '短期上下文、任务状态、长期记忆和外部文件系统承担不同角色。',
        nodes: ['上下文窗口', '任务状态', '长期记忆'],
        flow: ['观察', '写入', '检索', '更新'],
        note: '记忆不是越多越好，关键是何时写、何时忘。',
        accent: '#fb7185',
      },
    ],
  },
  {
    moduleDir: '09_inference_system',
    moduleId: '09',
    moduleName: '推理系统',
    icon: '⚙️',
    aiLens: 'AI 眼里的推理系统是把每个 token 的延迟、显存、吞吐和成本同时压到可接受范围。',
    sketches: [
      {
        slug: 'prefill-decode-kv',
        title: 'Prefill 和 Decode 是两种工作负载',
        question: '为什么首字慢、后续又不同？',
        thesis: 'Prefill 吃算力，Decode 吃显存带宽和 KV Cache 管理。',
        nodes: ['Prompt Prefill', 'KV Cache', 'Token Decode'],
        flow: ['输入', '建缓存', '逐 token', '输出'],
        note: '优化推理先分清 TTFT 和 TPOT。',
        accent: '#f59e0b',
      },
      {
        slug: 'continuous-batching',
        title: '连续批处理像机场调度',
        question: '请求长短不一怎么提高吞吐？',
        thesis: '动态加入、退出和重排请求，让 GPU 尽量保持忙碌。',
        nodes: ['请求队列', 'Scheduler', 'Batch'],
        flow: ['到达', '拼批', '执行', '释放'],
        note: '吞吐提升常来自更聪明的调度。',
        accent: '#38bdf8',
      },
      {
        slug: 'serving-economics',
        title: '服务经济学决定架构',
        question: '为什么推理不是只看 QPS？',
        thesis: '延迟 SLO、显存占用、缓存命中、并发和卡价共同决定单位 token 成本。',
        nodes: ['Latency SLO', 'GPU 利用率', 'Token 成本'],
        flow: ['流量', '容量', '成本', '体验'],
        note: '推理系统最后要对业务账本负责。',
        accent: '#22c55e',
      },
    ],
  },
  {
    moduleDir: '10_ai_related_course',
    moduleId: '10',
    moduleName: 'AI相关课程',
    icon: '🎓',
    aiLens: 'AI 眼里的课程应该把概念、实操、反馈和复盘串成学习闭环。',
    sketches: [
      {
        slug: 'learning-map',
        title: '先建学习地图',
        question: 'AI Infra 入门从哪开始？',
        thesis: '硬件、编程、训练、推理、应用要先建立整体坐标，再逐块深入。',
        nodes: ['全局图', '关键术语', '学习路径'],
        flow: ['概览', '主题', '练习', '复盘'],
        note: '地图让细节不再漂浮。',
        accent: '#84cc16',
      },
      {
        slug: 'lab-first',
        title: '实验比背概念更快',
        question: '怎么把知识变成能力？',
        thesis: '用最小实验连接命令、指标、代码和系统现象。',
        nodes: ['小实验', '可观测指标', '错误记录'],
        flow: ['搭环境', '跑样例', '改参数', '看结果'],
        note: 'AI 学习最怕只看不跑。',
        accent: '#60a5fa',
      },
      {
        slug: 'portfolio-loop',
        title: '作品集反推学习',
        question: '怎么确认自己真的会了？',
        thesis: '把课程输出变成文章、Demo、脚本和复盘，形成可复用资产。',
        nodes: ['Demo', '文档', '复盘'],
        flow: ['问题', '方案', '结果', '沉淀'],
        note: '能教别人，通常才是真的掌握。',
        accent: '#f97316',
      },
    ],
  },
  {
    moduleDir: '98_llm_programming',
    moduleId: '11',
    moduleName: 'LLM编程',
    icon: '💻',
    aiLens: 'AI 眼里的 LLM 编程是围绕模型不确定性设计状态、评测、工具和回滚。',
    sketches: [
      {
        slug: 'stateful-graph',
        title: '状态图让应用可控',
        question: '为什么需要 LangGraph 这类框架？',
        thesis: '节点、边、状态和条件跳转把一次性生成变成可审计流程。',
        nodes: ['State', 'Node', 'Edge'],
        flow: ['输入', '状态', '决策', '输出'],
        note: '复杂 LLM 应用一定会长出状态机。',
        accent: '#2dd4bf',
      },
      {
        slug: 'harness-engineering',
        title: 'Harness 包住模型不确定性',
        question: '怎么让 LLM 应用工程化？',
        thesis: 'Prompt、工具、缓存、测试、评测和回退共同构成应用外壳。',
        nodes: ['Prompt', 'Eval', 'Fallback'],
        flow: ['需求', '实现', '评测', '发布'],
        note: '模型只是内核，Harness 才是产品。',
        accent: '#facc15',
      },
      {
        slug: 'coding-agent-loop',
        title: 'Coding Agent 需要工作区意识',
        question: 'AI 写代码如何更可靠？',
        thesis: '读代码、计划、改动、运行测试、解释差异，是代码智能体的基本循环。',
        nodes: ['Repo Context', 'Patch', 'Tests'],
        flow: ['理解', '编辑', '验证', '交付'],
        note: '让 Agent 看见反馈，它才会变得稳。',
        accent: '#e879f9',
      },
    ],
  },
  {
    moduleDir: '99_tools_and_misc',
    moduleId: '12',
    moduleName: '实用工具与杂项',
    icon: '🛠️',
    aiLens: 'AI 眼里的工具是缩短反馈回路的杠杆：本地运行、评测、调试和自动化都服务于更快学习。',
    sketches: [
      {
        slug: 'local-model-stack',
        title: '本地模型栈适合快速试错',
        question: '为什么还要本地部署？',
        thesis: 'Ollama、llama.cpp、量化模型和本地数据让实验成本低、隐私边界清楚。',
        nodes: ['模型文件', '运行时', '本地数据'],
        flow: ['下载', '启动', '调用', '观察'],
        note: '本地不是替代云，而是缩短实验路径。',
        accent: '#14b8a6',
      },
      {
        slug: 'benchmark-ladder',
        title: 'Benchmark 要分层看',
        question: '工具和模型怎么比较？',
        thesis: '微基准、任务评测、用户体验和成本评估回答不同问题。',
        nodes: ['Microbench', 'Task Eval', 'Cost'],
        flow: ['指标', '样本', '运行', '对比'],
        note: '一个分数无法代表一个系统。',
        accent: '#fb7185',
      },
      {
        slug: 'toolbox-automation',
        title: '工具箱要能串成流程',
        question: '杂项工具怎么不变成杂乱？',
        thesis: '把 CLI、脚本、模板、监控和文档串成可复用自动化。',
        nodes: ['CLI', '脚本', '模板'],
        flow: ['输入', '处理', '检查', '输出'],
        note: '好工具会把重复劳动变成按钮。',
        accent: '#38bdf8',
      },
    ],
  },
];

export function getSketchModule(moduleDir: string): SketchModule | undefined {
  return SKETCH_MODULES.find(module => module.moduleDir === moduleDir);
}

export function countSketches(): number {
  const moduleSketches = SKETCH_MODULES.reduce((sum, module) => sum + module.sketches.length, 0);
  const transitionSketches = IAAS_TRANSITION_TRACKS.reduce((sum, track) => sum + track.sketches.length, 0);
  return moduleSketches + transitionSketches;
}
